// Type declarations for the WASM module generated by wasm-pack

// Default export: WASM initialization function
export default function init(input?: RequestInfo | URL | Response | BufferSource | WebAssembly.Module): Promise<void>;

// Interpreter class exported by wasm-bindgen
export class Interpreter {
  constructor();
  execute(input: string): string;
  get_stack_json(): string;
  get_dictionary_json(): string;
  get_output(): string;
  save_state(): string;
  load_state(state: string): void;
}
